sonar.projectKey=ModuloCompresion
sonar.working.directory=C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION
sonar.pullrequest.cache.basepath=C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION
sonar.sources=\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\RAR\\WinFormsAppRAR\\.vs\\WinFormsAppRAR.slnx\\v18\\DocumentLayout.backup.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\RAR\\WinFormsAppRAR\\.vs\\WinFormsAppRAR.slnx\\v18\\DocumentLayout.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\RAR\\WinFormsAppRAR\\.vs\\WinFormsAppRAR.slnx\\v18\\ResourceExplorer\\settings.json"

0F8F3942-751C-ABEC-E6D1-217F1BA96EDC.sonar.projectKey=ModuloCompresion:0F8F3942-751C-ABEC-E6D1-217F1BA96EDC
0F8F3942-751C-ABEC-E6D1-217F1BA96EDC.sonar.projectName=WinFormsAppRAR
0F8F3942-751C-ABEC-E6D1-217F1BA96EDC.sonar.projectBaseDir=C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\RAR\\WinFormsAppRAR\\WinFormsAppRAR
0F8F3942-751C-ABEC-E6D1-217F1BA96EDC.sonar.sourceEncoding=utf-8
0F8F3942-751C-ABEC-E6D1-217F1BA96EDC.sonar.tests=
0F8F3942-751C-ABEC-E6D1-217F1BA96EDC.sonar.sources=\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\RAR\\WinFormsAppRAR\\WinFormsAppRAR\\EstelaRar.cs",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\RAR\\WinFormsAppRAR\\WinFormsAppRAR\\Form1.cs",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\RAR\\WinFormsAppRAR\\WinFormsAppRAR\\Form1.Designer.cs",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\RAR\\WinFormsAppRAR\\WinFormsAppRAR\\Program.cs",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\RAR\\WinFormsAppRAR\\WinFormsAppRAR\\Form1.resx",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\RAR\\WinFormsAppRAR\\WinFormsAppRAR\\obj\\project.assets.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\RAR\\WinFormsAppRAR\\WinFormsAppRAR\\obj\\WinFormsAppRAR.csproj.nuget.dgspec.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\RAR\\WinFormsAppRAR\\WinFormsAppRAR\\bin\\Debug\\net10.0-windows\\WinFormsAppRAR.deps.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\RAR\\WinFormsAppRAR\\WinFormsAppRAR\\bin\\Debug\\net10.0-windows\\WinFormsAppRAR.runtimeconfig.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\RAR\\WinFormsAppRAR\\WinFormsAppRAR\\obj\\Debug\\net10.0-windows\\WinFormsAppRAR.designer.deps.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\RAR\\WinFormsAppRAR\\WinFormsAppRAR\\obj\\Debug\\net10.0-windows\\WinFormsAppRAR.designer.runtimeconfig.json"

0F8F3942-751C-ABEC-E6D1-217F1BA96EDC.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\.sonarqube\\out\\0"
0F8F3942-751C-ABEC-E6D1-217F1BA96EDC.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\.sonarqube\\out\\0\\Issues.json"
0F8F3942-751C-ABEC-E6D1-217F1BA96EDC.sonar.cs.scanner.telemetry=\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\.sonarqube\\out\\0\\Telemetry.json"

0F8F3942-751C-ABEC-E6D1-217F1BA96EDC.sonar.working.directory=C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\.sonarqube\\out\\.sonar\\mod0
F35E45A5-4335-82E0-0EA3-59E0BC99D09B.sonar.projectKey=ModuloCompresion:F35E45A5-4335-82E0-0EA3-59E0BC99D09B
F35E45A5-4335-82E0-0EA3-59E0BC99D09B.sonar.projectName=WinFormsLZMA
F35E45A5-4335-82E0-0EA3-59E0BC99D09B.sonar.projectBaseDir=C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\LZMA\\WinFormsLZMA
F35E45A5-4335-82E0-0EA3-59E0BC99D09B.sonar.sourceEncoding=utf-8
F35E45A5-4335-82E0-0EA3-59E0BC99D09B.sonar.tests=
F35E45A5-4335-82E0-0EA3-59E0BC99D09B.sonar.sources=\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\LZMA\\WinFormsLZMA\\obj\\project.assets.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\LZMA\\WinFormsLZMA\\obj\\WinFormsLZMA.csproj.nuget.dgspec.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\LZMA\\WinFormsLZMA\\bin\\Debug\\net8.0-windows\\WinFormsLZMA.deps.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\LZMA\\WinFormsLZMA\\bin\\Debug\\net8.0-windows\\WinFormsLZMA.runtimeconfig.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\LZMA\\WinFormsLZMA\\obj\\Debug\\net8.0-windows\\WinFormsLZMA.designer.deps.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\LZMA\\WinFormsLZMA\\obj\\Debug\\net8.0-windows\\WinFormsLZMA.designer.runtimeconfig.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\LZMA\\WinFormsLZMA\\Form1.cs",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\LZMA\\WinFormsLZMA\\Form1.Designer.cs",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\LZMA\\WinFormsLZMA\\Program.cs",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\LZMA\\WinFormsLZMA\\RomeroLzma.cs",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\LZMA\\WinFormsLZMA\\Form1.resx"

F35E45A5-4335-82E0-0EA3-59E0BC99D09B.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\.sonarqube\\out\\1"
F35E45A5-4335-82E0-0EA3-59E0BC99D09B.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\.sonarqube\\out\\1\\Issues.json"
F35E45A5-4335-82E0-0EA3-59E0BC99D09B.sonar.cs.scanner.telemetry=\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\.sonarqube\\out\\1\\Telemetry.json"

F35E45A5-4335-82E0-0EA3-59E0BC99D09B.sonar.working.directory=C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\.sonarqube\\out\\.sonar\\mod1
780E7581-9BFA-CF58-64D3-C011353E52B3.sonar.projectKey=ModuloCompresion:780E7581-9BFA-CF58-64D3-C011353E52B3
780E7581-9BFA-CF58-64D3-C011353E52B3.sonar.projectName=zipChecya
780E7581-9BFA-CF58-64D3-C011353E52B3.sonar.projectBaseDir=C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\ZIP\\zipChecya
780E7581-9BFA-CF58-64D3-C011353E52B3.sonar.sourceEncoding=utf-8
780E7581-9BFA-CF58-64D3-C011353E52B3.sonar.tests=
780E7581-9BFA-CF58-64D3-C011353E52B3.sonar.sources=\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\ZIP\\zipChecya\\obj\\project.assets.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\ZIP\\zipChecya\\obj\\zipChecya.csproj.nuget.dgspec.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\ZIP\\zipChecya\\.vs\\zipChecya.slnx\\v18\\DocumentLayout.backup.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\ZIP\\zipChecya\\.vs\\zipChecya.slnx\\v18\\DocumentLayout.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\ZIP\\zipChecya\\bin\\Debug\\net10.0-windows\\zipChecya.deps.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\ZIP\\zipChecya\\bin\\Debug\\net10.0-windows\\zipChecya.runtimeconfig.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\ZIP\\zipChecya\\obj\\Debug\\net10.0-windows\\zipChecya.designer.deps.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\ZIP\\zipChecya\\obj\\Debug\\net10.0-windows\\zipChecya.designer.runtimeconfig.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\ZIP\\zipChecya\\CompresorZip.cs",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\ZIP\\zipChecya\\Form1.cs",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\ZIP\\zipChecya\\Form1.Designer.cs",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\ZIP\\zipChecya\\Program.cs",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\ZIP\\zipChecya\\Form1.resx"

780E7581-9BFA-CF58-64D3-C011353E52B3.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\.sonarqube\\out\\2"
780E7581-9BFA-CF58-64D3-C011353E52B3.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\.sonarqube\\out\\2\\Issues.json"
780E7581-9BFA-CF58-64D3-C011353E52B3.sonar.cs.scanner.telemetry=\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\.sonarqube\\out\\2\\Telemetry.json"

780E7581-9BFA-CF58-64D3-C011353E52B3.sonar.working.directory=C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\.sonarqube\\out\\.sonar\\mod2
01A26A4C-F3C9-477C-A690-9C57DB6EC877.sonar.projectKey=ModuloCompresion:01A26A4C-F3C9-477C-A690-9C57DB6EC877
01A26A4C-F3C9-477C-A690-9C57DB6EC877.sonar.projectName=zipChecya.Tests
01A26A4C-F3C9-477C-A690-9C57DB6EC877.sonar.projectBaseDir=C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\zipChecya.Tests
01A26A4C-F3C9-477C-A690-9C57DB6EC877.sonar.sourceEncoding=utf-8
01A26A4C-F3C9-477C-A690-9C57DB6EC877.sonar.sources=
01A26A4C-F3C9-477C-A690-9C57DB6EC877.sonar.tests=\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\zipChecya.Tests\\obj\\project.assets.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\zipChecya.Tests\\obj\\zipChecya.Tests.csproj.nuget.dgspec.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\zipChecya.Tests\\bin\\Debug\\net10.0-windows\\zipChecya.deps.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\zipChecya.Tests\\bin\\Debug\\net10.0-windows\\zipChecya.runtimeconfig.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\zipChecya.Tests\\bin\\Debug\\net10.0-windows\\zipChecya.Tests.deps.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\zipChecya.Tests\\bin\\Debug\\net10.0-windows\\zipChecya.Tests.runtimeconfig.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\zipChecya.Tests\\bin\\Debug\\net10.0-windows\\runtimes\\linux-musl-x64\\native\\Cov_x64.config",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\zipChecya.Tests\\bin\\Debug\\net10.0-windows\\runtimes\\linux-x64\\native\\Cov_x64.config",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\zipChecya.Tests\\bin\\Debug\\net10.0-windows\\runtimes\\osx-x64\\native\\Cov_x64.config",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\zipChecya.Tests\\bin\\Debug\\net10.0-windows\\runtimes\\win-arm64\\native\\Cov_arm64.config",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\zipChecya.Tests\\bin\\Debug\\net10.0-windows\\runtimes\\win-arm64\\native\\Cov_x64.config",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\zipChecya.Tests\\bin\\Debug\\net10.0-windows\\runtimes\\win-arm64\\native\\Cov_x86.config",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\zipChecya.Tests\\bin\\Debug\\net10.0-windows\\runtimes\\win-x64\\native\\Cov_arm64.config",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\zipChecya.Tests\\bin\\Debug\\net10.0-windows\\runtimes\\win-x64\\native\\Cov_x64.config",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\zipChecya.Tests\\bin\\Debug\\net10.0-windows\\runtimes\\win-x64\\native\\Cov_x86.config",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\zipChecya.Tests\\bin\\Debug\\net10.0-windows\\runtimes\\win-x86\\native\\Cov_arm64.config",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\zipChecya.Tests\\bin\\Debug\\net10.0-windows\\runtimes\\win-x86\\native\\Cov_x64.config",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\zipChecya.Tests\\bin\\Debug\\net10.0-windows\\runtimes\\win-x86\\native\\Cov_x86.config",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\zipChecya.Tests\\MSTestSettings.cs",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\zipChecya.Tests\\Test1.cs"

01A26A4C-F3C9-477C-A690-9C57DB6EC877.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\.sonarqube\\out\\3"
01A26A4C-F3C9-477C-A690-9C57DB6EC877.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\.sonarqube\\out\\3\\Issues.json"
01A26A4C-F3C9-477C-A690-9C57DB6EC877.sonar.cs.scanner.telemetry=\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\.sonarqube\\out\\3\\Telemetry.json"

01A26A4C-F3C9-477C-A690-9C57DB6EC877.sonar.working.directory=C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\.sonarqube\\out\\.sonar\\mod3
5EF13ADD-9EAE-3351-599A-94BD70A01D68.sonar.projectKey=ModuloCompresion:5EF13ADD-9EAE-3351-599A-94BD70A01D68
5EF13ADD-9EAE-3351-599A-94BD70A01D68.sonar.projectName=ModuloCompresion
5EF13ADD-9EAE-3351-599A-94BD70A01D68.sonar.projectBaseDir=C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\ModuloCompresion
5EF13ADD-9EAE-3351-599A-94BD70A01D68.sonar.sourceEncoding=utf-8
5EF13ADD-9EAE-3351-599A-94BD70A01D68.sonar.tests=
5EF13ADD-9EAE-3351-599A-94BD70A01D68.sonar.sources=\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\ModuloCompresion\\obj\\ModuloCompresion.csproj.nuget.dgspec.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\ModuloCompresion\\obj\\project.assets.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\ModuloCompresion\\.vs\\ModuloCompresion.slnx\\v18\\DocumentLayout.backup.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\ModuloCompresion\\.vs\\ModuloCompresion.slnx\\v18\\DocumentLayout.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\ModuloCompresion\\bin\\Debug\\net10.0-windows\\ModuloCompresion.deps.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\ModuloCompresion\\bin\\Debug\\net10.0-windows\\ModuloCompresion.runtimeconfig.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\ModuloCompresion\\bin\\Debug\\net10.0-windows\\WinFormsAppRAR.deps.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\ModuloCompresion\\bin\\Debug\\net10.0-windows\\WinFormsAppRAR.runtimeconfig.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\ModuloCompresion\\bin\\Debug\\net10.0-windows\\WinFormsLZMA.deps.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\ModuloCompresion\\bin\\Debug\\net10.0-windows\\WinFormsLZMA.runtimeconfig.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\ModuloCompresion\\bin\\Debug\\net10.0-windows\\zipChecya.deps.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\ModuloCompresion\\bin\\Debug\\net10.0-windows\\zipChecya.runtimeconfig.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\ModuloCompresion\\obj\\Debug\\net10.0-windows\\ModuloCompresion.designer.deps.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\ModuloCompresion\\obj\\Debug\\net10.0-windows\\ModuloCompresion.designer.runtimeconfig.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\ModuloCompresion\\Form1.cs",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\ModuloCompresion\\Form1.Designer.cs",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\ModuloCompresion\\Program.cs",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\ModuloCompresion\\Form1.resx",\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\ModuloCompresion\\Properties\\Resources.resx"

5EF13ADD-9EAE-3351-599A-94BD70A01D68.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\.sonarqube\\out\\4"
5EF13ADD-9EAE-3351-599A-94BD70A01D68.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\.sonarqube\\out\\4\\Issues.json"
5EF13ADD-9EAE-3351-599A-94BD70A01D68.sonar.cs.scanner.telemetry=\
"C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\.sonarqube\\out\\4\\Telemetry.json"

5EF13ADD-9EAE-3351-599A-94BD70A01D68.sonar.working.directory=C:\\Users\\DIEGCOP20\\Desktop\\MODULO DE COMPRESION\\.sonarqube\\out\\.sonar\\mod4
sonar.host.url=http://localhost:9000
sonar.visualstudio.enable=false

sonar.modules=0F8F3942-751C-ABEC-E6D1-217F1BA96EDC,F35E45A5-4335-82E0-0EA3-59E0BC99D09B,780E7581-9BFA-CF58-64D3-C011353E52B3,01A26A4C-F3C9-477C-A690-9C57DB6EC877,5EF13ADD-9EAE-3351-599A-94BD70A01D68

