sonar.projectKey=winbackup-modulo-compresion
sonar.working.directory=C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app
sonar.pullrequest.cache.basepath=C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app

B318907A-E7FC-C7D8-3AFA-CC6E68C60D1C.sonar.projectKey=winbackup-modulo-compresion:B318907A-E7FC-C7D8-3AFA-CC6E68C60D1C
B318907A-E7FC-C7D8-3AFA-CC6E68C60D1C.sonar.projectName=winbackup
B318907A-E7FC-C7D8-3AFA-CC6E68C60D1C.sonar.projectBaseDir=C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\winbackup
B318907A-E7FC-C7D8-3AFA-CC6E68C60D1C.sonar.sourceEncoding=utf-8
B318907A-E7FC-C7D8-3AFA-CC6E68C60D1C.sonar.tests=
B318907A-E7FC-C7D8-3AFA-CC6E68C60D1C.sonar.sources=\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\winbackup\\clconfiguracion.cs",\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\winbackup\\clseguridad.cs",\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\winbackup\\compresion\\CompresionCab.cs",\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\winbackup\\compresion\\CompresionFactory.cs",\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\winbackup\\compresion\\CompresionGzip.cs",\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\winbackup\\compresion\\CompresionLzma.cs",\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\winbackup\\compresion\\CompresionRar.cs",\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\winbackup\\compresion\\CompresionTar.cs",\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\winbackup\\compresion\\CompresionZip.cs",\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\winbackup\\compresion\\ICompresion.cs",\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\winbackup\\Form1.cs",\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\winbackup\\Form1.Designer.cs",\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\winbackup\\GlobalData.cs",\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\winbackup\\Program.cs",\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\winbackup\\Form1.resx",\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\winbackup\\config.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\winbackup\\obj\\project.assets.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\winbackup\\obj\\winbackup.csproj.nuget.dgspec.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\winbackup\\.vs\\winbackup.slnx\\v18\\DocumentLayout.backup.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\winbackup\\.vs\\winbackup.slnx\\v18\\DocumentLayout.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\winbackup\\bin\\Debug\\net8.0-windows\\winbackup.deps.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\winbackup\\bin\\Debug\\net8.0-windows\\winbackup.runtimeconfig.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\winbackup\\obj\\Debug\\net8.0-windows\\winbackup.sourcelink.json"

B318907A-E7FC-C7D8-3AFA-CC6E68C60D1C.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\.sonarqube\\out\\0"
B318907A-E7FC-C7D8-3AFA-CC6E68C60D1C.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\.sonarqube\\out\\0\\Issues.json"
B318907A-E7FC-C7D8-3AFA-CC6E68C60D1C.sonar.cs.scanner.telemetry=\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\.sonarqube\\out\\0\\Telemetry.json"

B318907A-E7FC-C7D8-3AFA-CC6E68C60D1C.sonar.working.directory=C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\.sonarqube\\out\\.sonar\\mod0
F4B0A766-804A-49BE-AF92-818C8C92FAD0.sonar.projectKey=winbackup-modulo-compresion:F4B0A766-804A-49BE-AF92-818C8C92FAD0
F4B0A766-804A-49BE-AF92-818C8C92FAD0.sonar.projectName=winbackup.Tests
F4B0A766-804A-49BE-AF92-818C8C92FAD0.sonar.projectBaseDir=C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\winbackup.Tests
F4B0A766-804A-49BE-AF92-818C8C92FAD0.sonar.sourceEncoding=utf-8
F4B0A766-804A-49BE-AF92-818C8C92FAD0.sonar.sources=
F4B0A766-804A-49BE-AF92-818C8C92FAD0.sonar.tests=\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\winbackup.Tests\\obj\\project.assets.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\winbackup.Tests\\obj\\winbackup.Tests.csproj.nuget.dgspec.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\winbackup.Tests\\bin\\Debug\\net8.0-windows\\winbackup.deps.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\winbackup.Tests\\bin\\Debug\\net8.0-windows\\winbackup.runtimeconfig.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\winbackup.Tests\\bin\\Debug\\net8.0-windows\\winbackup.Tests.deps.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\winbackup.Tests\\bin\\Debug\\net8.0-windows\\winbackup.Tests.runtimeconfig.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\winbackup.Tests\\obj\\Debug\\net8.0-windows\\winbackup.Tests.sourcelink.json",\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\winbackup.Tests\\bin\\Debug\\net8.0-windows\\runtimes\\linux-musl-x64\\native\\Cov_x64.config",\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\winbackup.Tests\\bin\\Debug\\net8.0-windows\\runtimes\\linux-x64\\native\\Cov_x64.config",\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\winbackup.Tests\\bin\\Debug\\net8.0-windows\\runtimes\\osx-x64\\native\\Cov_x64.config",\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\winbackup.Tests\\bin\\Debug\\net8.0-windows\\runtimes\\win-arm64\\native\\Cov_arm64.config",\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\winbackup.Tests\\bin\\Debug\\net8.0-windows\\runtimes\\win-arm64\\native\\Cov_x64.config",\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\winbackup.Tests\\bin\\Debug\\net8.0-windows\\runtimes\\win-arm64\\native\\Cov_x86.config",\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\winbackup.Tests\\bin\\Debug\\net8.0-windows\\runtimes\\win-x64\\native\\Cov_arm64.config",\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\winbackup.Tests\\bin\\Debug\\net8.0-windows\\runtimes\\win-x64\\native\\Cov_x64.config",\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\winbackup.Tests\\bin\\Debug\\net8.0-windows\\runtimes\\win-x64\\native\\Cov_x86.config",\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\winbackup.Tests\\bin\\Debug\\net8.0-windows\\runtimes\\win-x86\\native\\Cov_arm64.config",\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\winbackup.Tests\\bin\\Debug\\net8.0-windows\\runtimes\\win-x86\\native\\Cov_x64.config",\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\winbackup.Tests\\bin\\Debug\\net8.0-windows\\runtimes\\win-x86\\native\\Cov_x86.config",\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\winbackup.Tests\\clconfiguracionTests.cs",\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\winbackup.Tests\\clseguridadTests.cs",\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\winbackup.Tests\\CompresionTests.cs",\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\winbackup.Tests\\GlobalDataTests.cs",\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\winbackup.Tests\\MSTestSettings.cs",\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\winbackup.Tests\\Test1.cs"

F4B0A766-804A-49BE-AF92-818C8C92FAD0.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\.sonarqube\\out\\1"
F4B0A766-804A-49BE-AF92-818C8C92FAD0.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\.sonarqube\\out\\1\\Issues.json"
F4B0A766-804A-49BE-AF92-818C8C92FAD0.sonar.cs.scanner.telemetry=\
"C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\.sonarqube\\out\\1\\Telemetry.json"

F4B0A766-804A-49BE-AF92-818C8C92FAD0.sonar.working.directory=C:\\Users\\DIEGCOP20\\Desktop\\winbackup-app\\.sonarqube\\out\\.sonar\\mod1
sonar.host.url=http://localhost:9000
sonar.visualstudio.enable=false

sonar.modules=B318907A-E7FC-C7D8-3AFA-CC6E68C60D1C,F4B0A766-804A-49BE-AF92-818C8C92FAD0

